<?php get_header(); ?>
    <?php get_template_part('about-page/hero-section'); ?>
    <?php get_template_part('about-page/two-column-section'); ?>
    <?php get_template_part('about-page/mission-section'); ?>
    <?php get_template_part('about-page/text-icon-section'); ?>
    <?php get_template_part('about-page/history-section'); ?>
    <?php get_template_part('about-page/organization-section'); ?>
    <?php get_template_part('about-page/sponsors-section'); ?>
<?php get_footer(); ?>
